### PR TITLE
Fix #71 style undefined

### LINKED ISSUE #71: Cannot read property 'style' of undefined
On line 152 of ng2-auto-complete.directive.ts, there is a reference to component.inputEl. While component is defined, inputEl is not and so I get the following console error: 

core.umd.js:2844 TypeError: Cannot read property 'style' of undefined
    at Ng2AutoCompleteDirective.styleAutoCompleteDropdown (ng2-auto-complete.directive.ts:152)
    at ZoneDelegate.invokeTask (zone.js:236)
    at Object.onInvokeTask (core.umd.js:5967)
    at ZoneDelegate.invokeTask (zone.js:235)
    at Zone.runTask (zone.js:136)
    at ZoneTask.invoke (zone.js:304)

### PR DESCRIPTION
**Pull request by ndcunningham**
Fix #71 style undefined

### CODE REVIEW

File: src/ng2-auto-complete.component.ts [hunk 1]
```diff
@@ -138,10 +140,8 @@ export class Ng2AutoCompleteComponent implements OnInit {
   /**
    * constructor
    */
-  constructor(
```
Comment (allenhwkim) [inline src/ng2-auto-complete.component.ts]: Let us not change this style, unless you do have a clear reason to do so. e.g., Industry standard or community recommendation.

File: src/ng2-auto-complete.component.ts [hunk 2]
```diff
@@ -138,10 +140,8 @@ export class Ng2AutoCompleteComponent implements OnInit {
...
-    elementRef: ElementRef,
-    public autoComplete: Ng2AutoComplete
-  ) {
+  constructor(elementRef: ElementRef,
+              public autoComplete: Ng2AutoComplete) {
```
Comment (allenhwkim) [inline src/ng2-auto-complete.component.ts]: Let's not change the style unless it is an industry standard or community recommended

File: src/ng2-auto-complete.directive.ts [hunk 3]
```diff
@@ -46,6 +47,7 @@ export class Ng2AutoCompleteDirective implements OnInit {
   inputEl: HTMLInputElement;  // input tag
 
   constructor(private resolver: ComponentFactoryResolver,
+              private renderer: Renderer,
               public  viewContainerRef: ViewContainerRef) {
     this.el = this.viewContainerRef.element.nativeElement;
   }
```
Comment (allenhwkim) [inline src/ng2-auto-complete.directive.ts]: The same thing, let's keep two space indentation rather than having ruby-on-rails like coding style.

File: src/ng2-auto-complete.component.ts [hunk 4]
```diff
@@ -5,23 +5,24 @@ import {
   Output,
   OnInit,
   ViewEncapsulation,
-  EventEmitter
+  EventEmitter,
+  ViewChild
 } from "@angular/core";
-import { Ng2AutoComplete } from "./ng2-auto-complete";
+import {Ng2AutoComplete} from "./ng2-auto-complete";
```
Comment (allenhwkim) [inline src/ng2-auto-complete.component.ts]: Coding style conflict. Could you please provide clear reason why use {XXX} instead of { XXX }?

Comment (ndcunningham) [inline src/ng2-auto-complete.component.ts]: I'll update them all. Angular team has no spaces around their imports in their code: 

But their style guide uses spaces very conflicting. If the communities choice is spaces i can update.

File: src/ng2-auto-complete.directive.ts (hunk 3 above)
Comment (ndcunningham) [inline src/ng2-auto-complete.directive.ts]: i blame webstorm!

i would rather something like 
```
constructor(
  private A,
  private B) {}
```
If this is fine I'll change them all to match

File: src/ng2-auto-complete.component.ts (hunk 2 above)
Comment (ndcunningham) [inline src/ng2-auto-complete.component.ts]: Yea their standard is not to go over certain line count for their code.

so it's either
```
constructor(
  private alksjdghbajkhsdasd, private auoiskgdgasd
  priavte asdasda){}
```
